// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbirevaryjmyinuzxlvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiaXJldmFyeWpteWludXp4bHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNTA0NDEsImV4cCI6MjA4ODkyNjQ0MX0.LkDbxO_tDoRBwy3-R4wtmTlioKROIIqhYw43ipTHvrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});